### ISSUE TITLE
Display the real (local) user progress in the course sidebar

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/saiba#164]
### Feature description

We need to display the real user progress in the course sidebar, the same way that we do it on Platypus.

This issue only requires to display the user progress stored locally (client-side).

### Depedencies

This issue depends on:

- #35 

### Out of scope

- Anything related to the "next" and "previous" buttons at the bottom of the page

### Additional information

Example of current implementation: https://learn.qiskit.org/course/introduction/why-quantum-computing

![image](https://user-images.githubusercontent.com/22047320/188858693-36dc5050-9507-4fd8-b41c-84d7b43de567.png)

**Comment by Tansito** [comment]
Issue delivered with #35
