### ISSUE TITLE
"Previous" and "Next" buttons at the end of the unit page

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/saiba#169]
### Feature description

We need to implement the "Previous" and "Next" buttons at the end of the unit pages like in Platypus.

### Additional information

![Screenshot 2022-09-07 at 14 40 20](https://user-images.githubusercontent.com/22047320/188880523-9f14ac20-aa89-4185-97a6-e9b1342c2433.png)

**Comment by vabarbosa** [comment]
duplicate of https://github.com/Qiskit/saiba/issues/205
