### ISSUE TITLE
Check the TypeScript compiler errors

### ISSUE THREAD

**Issue by abdonrd** [Qiskit/saiba#287]
Right we have TypeScript compiler errors, but we don't have any script to check it.

**Comment by Tansito** [comment]
Close in favor of #299

**Comment by abdonrd** [comment]
@Tansito they are different issues, this consists only of adding the task that checks for errors: https://github.com/Qiskit/saiba/pull/288

**Comment by Tansito** [comment]
Oh ok! I will add it to the planning then
