### ISSUE TITLE
Unit content not updated

### ISSUE THREAD

**Issue by yoshiemuranaka** [Qiskit/saiba#291]
### Steps to reproduce the problem

  1. Go to the home page
  2. Click on the second link
  3. Click the browser back button
  4. Click the last link
  5. See that the correct unit content doesn't load

### What is the current behavior?

The unit content page always renders the first unit content stored in the pinia store. 

### What is the expected behavior?

The unit content should be updated based on the course and unit slugs.

### Screenshots

https://user-images.githubusercontent.com/8097306/201138471-a2baa2fe-dc5f-4649-be41-5c5ee99a2590.mov

### Additional information

`hasActiveCourse` boolean does not trigger a change so the active unit in pinia store not properly updated

https://github.com/Qiskit/saiba/blob/main/pages/course/%5Bcourse%5D/%5Bunit%5D.vue#L73-L75

**Comment by yoshiemuranaka** [comment]
The unit content page is not properly updated because it is setting the "active unit" based on the unit slug. 

https://github.com/Qiskit/saiba/blob/main/store/unit/store.ts#L38-L40

For the new private content work, we have units with the same titles and slugs (eg `Get started` `Reflections`) across different courses

**Comment by Tansito** [comment]
@korgan00 if you can help @yoshiemuranaka here 🙏
