### ISSUE TITLE
Store user credentials in local-storage

### ISSUE THREAD

**Issue by Tansito** [Qiskit/saiba#297]
### Feature description

I would like to maintain my credentials even if I refresh the browser so I don't need to sign-in again in the application.

Once time I logs-out the data should be removed from local-storage.

**Comment by yoshiemuranaka** [comment]
The `/account` pages seem to persist the logged in state with the session cookie provided when authenticated. So another sign in is not required when a user refreshes the browser on these pages. We do need to investigate how to authenticate private course pages only (not public courses)

**Comment by yoshiemuranaka** [comment]
@abdonrd @Tansito is the `origin` field for courses public for all users even if unauthenticated?

**Comment by abdonrd** [comment]
> @abdonrd @Tansito is the `origin` field for courses public for all users even if unauthenticated?

It is not. Should?
The user does not need to filter by that field, right?

**Comment by Tansito** [comment]
My two cents here are that It doesn't matter for `unauthenticated` users. In fact I have pending a [little refactor](https://github.com/Qiskit/saiba/issues/298) that should join all the courses so, for a user I would say that a course is a course, `authenticated` or not independently the `origin` BUT it's an important field for the `/account` page to differentiate between `private` and `public` courses.

**Comment by abdonrd** [comment]
> My two cents here are that It doesn't matter for `unauthenticated` users. In fact I have pending a [little refactor](https://github.com/Qiskit/saiba/issues/298) that should join all the courses so, for a user I would say that a course is a course, `authenticated` or not independently the `origin` BUT it's an important field for the `/account` page to differentiate between `private` and `public` courses.

Agree!

**Comment by yoshiemuranaka** [comment]
Yep makes sense! I was trying to find a solution that would allow us to check whether or not the requested course is private or not (before accessing the content). 
But this isn't needed. @abdonrd found a nice way forward by storing the access token in local storage
