### ISSUE TITLE
Investigate at what point we should set as finished a course

### ISSUE THREAD

**Issue by Tansito** [Qiskit/saiba#308]
### Feature description
As an investigative story, the goal of this issue is to collab w/ the Design team, to arrive at the proper decisions. We should be able to answer the following:

**How does the platform determine:**
  - if a user has completed a course?
  - if a user has completed a unit?

**In regards to the UI,**
  - what does course completion look like?
  - what does unit completion look like?

**What is the defined user experience:**
  - for course completion?
  - for unit completion?

**Comment by Tansito** [comment]
Related with #160

**Comment by techtolentino** [comment]
**How does the platform determine if a user has completed a course?**
- A course is completed when all units are complete  
  - A unit is complete when the user finishes the lesson multiple-choice quiz, or checks off a box 

**In regards to the UI, what does course completion look like?**  
- on the Learn page, within a `MediaCard`, users can see how much of the course has been completed by looking at the subheader label, where we append the percentage of completion  
- once the user reaches the last page’s checkbox, and they complete that lesson, a Modal pops up letting them know that they’ve completed the entire Course  
- the confirmation button in that Modal can take the user back to their Learn page  


**In regards to the UI, what does unit completion look like?**  
- units are completed when a user has either finished the multiple-choice quiz at the end of the lesson or, when they check off a box indicating that "I've completed this lesson"
  



[Figma designs here](https://www.figma.com/file/KCfjq5xQHg0C1JmcrE3CGx/1332-Private-Experience?node-id=1881%3A160648&t=w3vFyc83QaL0oWuK-0)
