### ISSUE TITLE
As a learner, I want to see when I finished a course, so that we need to define when a course is finished

### ISSUE THREAD

**Issue by Tansito** [Qiskit/saiba#309]
### Background

For learners are interesting to now when they finished a course. Due to that we need to define when we consider a course finished and implement it.

### Goal

Close a course as finished.

### Acceptance criteria

- [ ] Set as completed a course when we consider that is completed

### Tasks

- #295 
- #308

**Comment by vabarbosa** [comment]
tasks here are completed. thank you!
