### ISSUE TITLE
User account content updates

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/saiba#314]
### Feature description

In the Account part of the application, we'll need to make the following updates:

- [x] "Private content" becomes “Accelerator content”
- [x] "Public content” becomes “Textbook content”
- [x] "Syllabi" becomes “Curated content”

- [x] "Learning" sidenav item becomes “Learn”
  - [x] update Learn page title
  - [x] update Learn page description

- [ ] Inactive tab colors should use cool gray
  - [ ] Add hover state colors (check w/ Design team)

### Additional information
[Tabs component in storybook](https://web-components.carbondesignsystem.com/?path=/story/components-tabs--default)

### Figma 
https://www.figma.com/file/TqhAqhKlyzVKMdWKas0lKI/1260-Curated-Syllabus?node-id=363%3A4874&t=VxaG7Z3Szm23kvUA-1

**Comment by abdonrd** [comment]
Part of this has been addressed here:
- https://github.com/Qiskit/saiba/pull/423
- https://github.com/Qiskit/saiba/pull/432

**Comment by abdonrd** [comment]
We can close this. Design changes are on hold.
