### ISSUE TITLE
Information architecture: Define all available routes

### ISSUE THREAD

**Issue by abdonrd** [Qiskit/saiba#316]
I think we should clarify (and write) what are the available routes.
We've had several conversations about URLs, but from time to time problems/doubts arise.

Related to:

- https://github.com/Qiskit/saiba/issues/306

**Comment by abdonrd** [comment]
My proposal is:


### Account

- `/account/learn`: Content explorer
- `/account/teach`: Content management
- `/account/profile`: Profile information

### Public Textbook Courses

- `/course/:courseSlug`: Course home
- `/course/:courseSlug/:unitSlug`: Course unit

### Syllabi

- `/syllabus/create`: Syllabus create
- `/syllabus/:syllabusCode`: Syllabus home
- `/syllabus/:syllabusCode/edit`: Syllabus management
- `/syllabus/:syllabusCode/:(unitId|unitSlug*)`

### Private Courses

- `/cohort/:cohortId`: Cohort home
- `/cohort/:cohortId/course/:courseSlug/:(unitId|unitSlug*)`: Course unit
  - Or could be like the public: `/course/:courseSlug/:(unitId|unitSlug*)`
- `/cohort/enrollment/:enrollmentCode`: Cohort enrollment
  - Or could be: `/account/learn?cohort-enrollment=enrollmentCode`

### Authentication

- `/signin`: Public sign in
- `/signin/private-experience`: Private sign in

---

- `courseSlug` is always unique.
- `syllabusCode` is always unique.
- `unitId` is always unique.
- `unitSlug*` should be always unique.

**Comment by yoshiemuranaka** [comment]
thanks @abdonrd this is super helpful!
Wondering about the private courses slug. since they are used for cohort management and also viewing it from the account related pages (with the account sidenav) should we use `account` instead of `course` ? maybe something like `account/teach/<course-slug>/edit`

**Comment by abdonrd** [comment]
I personally like to relate the URL to the model itself, and not from where it user comes. I mean:
- `/course/:courseSlug`
- `/course/:courseSlug/edit`

Since I imagine that maybe it can be reached from other pages: even from the view the course page, if you are an admin, we could show an edit button.

If we relate it to `/account`, we could suffer naming changes like:
- from `/classroom` to `/teach`
- from `/learning` to `/learng`

**Comment by yoshiemuranaka** [comment]
>I personally like to relate the URL to the model itself, and not from where it user comes. I mean:

I agree with this especially when designing APIs, but from a web/UI perspective, I am more in favor of the URL reflecting the context of the user in the UI, so if the user is still seeing the account layout and in an account flow, then to me `account` makes more sense. 

>And if we relate it to /account, we could suffer naming changes like:

Yes, I agree, this is an unavoidable problem when we change page names like classroom>teach


Just my opinion–I'm ok with whatever you decided

**Comment by yoshiemuranaka** [comment]
I'm working on #297. The issue I'm trying to resolve is enforcing authentication for private course content, but bypassing auth when a user is attempting to view a 'public' course content. 

The issue I'm running into is that our auth is handled in our router [middleware](https://github.com/Qiskit/saiba/blob/main/middleware/auth.ts) but currently there is no way to tell whether the course the user is attempting to fetch is public/private before actually fetching the course data. I do like the idea of the private and public course URLs following a the same format, but for this use case, it would be helpful if the URL could hint that the attempted path is private and therefore authentication is needed.

**Comment by abdonrd** [comment]
> > I personally like to relate the URL to the model itself, and not from where it user comes. I mean:
> 
> I agree with this especially when designing APIs, but from a web/UI perspective, I am more in favor of the URL reflecting the context of the user in the UI, so if the user is still seeing the account layout and in an account flow, then to me `account` makes more sense.

Right, I think you are right!

**Comment by abdonrd** [comment]
After today's meeting, it looks like we'll go with **Option 1** from https://github.com/Qiskit/saiba/issues/316#issuecomment-1316123470.

**Comment by abdonrd** [comment]
### Account

- `/account/learn`: Content explorer
- `/account/teach`: Content management
- `/account/profile`: Profile information

### Public Textbook Courses

- `/course/:courseSlug`: Course home
- `/course/:courseSlug/:unitSlug`: Course unit

### Private Courses

- `/account/teach/course/:courseSlug/edit`: Course management (and its cohorts)
- `/account/teach/course/:courseSlug/cohort/create`: Cohort create
- `/account/teach/course/:courseSlug/cohort/:cohortId/edit`: Cohort edit
- `/course/:courseSlug/:unitSlug`: Cohort course unit
  - Or `/cohort/:cohortId/course/:courseSlug/:unitSlug` if we need something special
- `/cohort/enrollment/:enrollmentCode`: Cohort enrollment
  - Or could be: `/account/learn?cohort-enrollment=enrollmentCode`

### Syllabi

- `/syllabus/create`: Syllabus create
- `/syllabus/:syllabusCode`: Syllabus home
- `/syllabus/:syllabusCode/edit`: Syllabus management
- `/syllabus/:syllabusCode/:unitSlug`: Syllabus unit

### Authentication

- `/signin`: Public sign in
- `/signin/private-experience`: Private sign in

---

- The `courseSlug` is unique like: `quantum-machine-learning`
  - We can auto-generate it based on the title

- The `unitSlug` is unique like: `introduction-999`
  - `-999` can be anything that makes it unique
  - We can auto-generate it based on the title
  - Note: As the public textbook courses URLs would be affected (because the `-999`), we need to create redirects so as not to lose any already shared/indexed links.

- The `cohortId` is unique auto-generated like: `a98189e2-972c-4ab5-b718-e38b8c14df0f`

- The `syllabusCode` is unique auto-generated like: `TRY-SW8`

- The `enrollmentCode` is unique auto-generated like: TODO

**Comment by eddybrando** [comment]
We need to create the issue. Then we'll close this.

**Comment by eddybrando** [comment]
The Epic including the relevant issues and information has been created: https://github.com/Qiskit/saiba/issues/374
