### ISSUE TITLE
Bug: Login issues for private experience 

### ISSUE THREAD

**Issue by alisonprose** [Qiskit/saiba#319]
### Steps to reproduce the problem
[The URL with the content issue.](https://saiba-staging.tfb1j0wd7x2.us-south.codeengine.appdomain.cloud/signin/private-experience)

Steps using Firefox or Safari:
  1. Enter URL in Firefox or Safari
  2. Select the IBMid button 
  3. Complete 2FA
  4. User is returned back to Login page
  5. Select the IBMid button again 
  6. User remains on login page, unable to navigate further

Steps using Chrome
  1. Enter URL in Chrome
  2. Select the IBMid button 
  3. Complete 2FA
  4. User is returned back to Login page
  5. User has to manually refresh to open Learning page
  5b. User is taken to a different page, not the Learning page
  5c. User is taken to Learning page, but not displayed any private content 

### What is the current behavior?
User is unable to proceed to the Learning page after attempted login 

### What is the expected behavior?
User should be able automatically navigated to the Learning page after a successful login

### Screenshots
Video screen recording posted in comments
Screenshots also provided in comments

### Device
MacBook Pro

### OS
MacOS Monterey

### Browser
Firefox

**Comment by alisonprose** [comment]
Screenshot for Steps using Chrome 5c.
![Screen Shot 2022-11-16 at 10 01 12 AM](https://user-images.githubusercontent.com/108363750/202231903-e7458122-1c2b-4e5b-8bc6-94fae7c69814.png)

**Comment by yoshiemuranaka** [comment]
Hi @alisonprose thanks for bringing this to our attention! Could you check whether or not you have cookies enabled in your browser preferences? I opened a similar issue #321 but was able to resolve it in Safari when I updated the settings https://github.com/Qiskit/saiba/issues/321#issuecomment-1332571874

>5b. User is taken to a different page, not the Learning page

The user should be redirected to the page they were previously on before signing in. If starting off on the signin page, the user should be redirected to the `Learning` page. This is the behavior I am seeing. Could you confirm whether or not this is still happening for you?


>5c. User is taken to Learning page, but not displayed any private content

I'm seeing your email added to the cohort, so I think you should be able to see the private course content on the `Learning` page now. Let me know if this is not the case.

**Comment by alisonprose** [comment]
@vabarbosa @yoshiemuranaka 
First, on Safari, I can confirm that I am able to proceed from Login to the Learning page once un-checking cross-site tracking and blocking cookies..although, it really seems like it's having cross-site tracking checked that triggers landing back on the login because I already had blocking cookies unchecked. 

Second, on Firefox, I can confirm that I am able to proceed to the Learning page when un-checking cookies only, which is opposite to the experience on Safari. I have attached screenshots of that experience for additional info. My question posted in a comment on issues #321 still remains...is this what we will need to explain to the clients in order to get around these authentication issues?

Third, on Chrome, I am no longer experience any issues from Login to the Learning page and have attached a screenshot of the browser settings as well.

Lastly, to assure I am not the only one having success, I would like to have a few other people test and will report back

<img width="905" alt="Screen Shot 2022-11-30 at 6 46 35 PM" src="https://user-images.githubusercontent.com/108363750/204954531-4d844ad5-a073-44dc-9424-0dd9eb7420bb.png">
<img width="704" alt="Screen Shot 2022-11-30 at 6 49 36 PM" src="https://user-images.githubusercontent.com/108363750/204954536-6b1183ea-05b9-4526-9157-4191bd66f14e.png">
<img width="641" alt="Screen Shot 2022-11-30 at 7 00 45 PM" src="https://user-images.githubusercontent.com/108363750/204956001-935e8209-06bd-4e81-ab85-ed4cb608a32c.png">

**Comment by yoshiemuranaka** [comment]
we are investigating whether or not the standard cookie consent flow would resolve the issue of users manually updating their browser preferences https://github.com/Qiskit/saiba/issues/329#issuecomment-1333436923

**Comment by yoshiemuranaka** [comment]
We believe the SSO issues are stemming from the staging URL not using the `qiskit.org` domain. More details in https://github.com/Qiskit/saiba/issues/329#issuecomment-1338108029

**Comment by abdonrd** [comment]
I close this issue to centralize the entire conversation in this other one: #329
