### ISSUE TITLE
SSO not working in Safari

### ISSUE THREAD

**Issue by yoshiemuranaka** [Qiskit/saiba#321]
### Steps to reproduce the problem

1. Open Safari browser
1. Go to saiba staging https://saiba-staging.tfb1j0wd7x2.us-south.codeengine.appdomain.cloud/signin
2. Try IBMid or Google SSO
3. Complete authentication steps
4. Try to access authenticated pages https://saiba-staging.tfb1j0wd7x2.us-south.codeengine.appdomain.cloud/account/admin
### What is the current behavior?

After authenticating attempting to a navigate to an authenticated page always redirects to sign in page

### What is the expected behavior?

After authenticating, the user should be redirected to the Learning page https://saiba-staging.tfb1j0wd7x2.us-south.codeengine.appdomain.cloud/account/learning

### Additional information

This issue seems to only happen in Safari. Confirmed flow worked in Chrome and Firefox

**Comment by yoshiemuranaka** [comment]
For me, when I allow cross-site tracking in the safari browser preference, this is no longer an issue

<img width="774" alt="Screenshot 2022-11-30 at 10 23 28 AM" src="https://user-images.githubusercontent.com/8097306/204879225-f871719a-6a70-45c5-9321-e561728140c5.png">

**Comment by vabarbosa** [comment]
@yoshiemuranaka thank you for investigating

@alisonprose this looks like it is related to a Safari setting. can you confirm updating the setting works for you (or whomever had similar issue)? thanks

**Comment by alisonprose** [comment]
@vabarbosa @yoshiemuranaka to make sure I understand correctly, we will have to instruct all clients with this authentication issue to disable these two browser preferences (prevent cross-site tracking and block all cookies) in order to proceed with learning? What if a client has restrictions from un-checking these due to company policy, how will we work around it then?

**Comment by abdonrd** [comment]
> For me, when I allow cross-site tracking in the safari browser preference, this is no longer an issue
> 
> <img alt="Screenshot 2022-11-30 at 10 23 28 AM" width="774" src="https://user-images.githubusercontent.com/8097306/204879225-f871719a-6a70-45c5-9321-e561728140c5.png">

I think we should expect some to have `Prevent cross-site tracking` selected.
We have to investigate if we can make it work anyway.

About cookies... They have to be enabled. But it is the default setting.

The default settings are:
- [x] Prevent cross-site tracking
- [ ] Block all cookies

**Comment by yoshiemuranaka** [comment]
The `Prevent cross-site tracking` feature does seem to block third-party cookies. not sure a way around this, but will do a bit more research tomorrow

>Unless you visit and interact with the third-party content provider as a first-party website, their [cookies and website data](https://support.apple.com/guide/safari/aside/glos0126d795/16.1/mac/13.0) are deleted.

https://support.apple.com/guide/safari/prevent-cross-site-tracking-sfri40732/mac

**Comment by yoshiemuranaka** [comment]
let's continue conversations in #329 
https://github.com/Qiskit/saiba/issues/329#issuecomment-1338108029
