### ISSUE TITLE
Improved cache configuration

### ISSUE THREAD

**Issue by Tansito** [Qiskit/saiba#330]
### What is the current behavior?

With the current configuration that we have if we create for example an `entity` we didn't receive it due to the cache because that cache is not reset. We should study the different options that we have to solve this:
- Reviewing the `TTL` for the `CACHE_SCHEMA`
- Review `CACHE_AUTO_PURGE` in case we want a more real time API (I liked this option).

### Additional information

https://docs.directus.io/self-hosted/config-options.html#cache

**Comment by Tansito** [comment]
Another issue that I would like to discuss with you @abdonrd when we can 🙏

**Comment by abdonrd** [comment]
Sure, let's investigate about it!

`CACHE_AUTO_PURGE` sounds really nice.

**Comment by abdonrd** [comment]
Done!
