### ISSUE TITLE
Create the "Cohorts List" page

### ISSUE THREAD

**Issue by korgan00** [Qiskit/saiba#332]
This Issue is only for creating the [Cohort List page](https://www.figma.com/file/KCfjq5xQHg0C1JmcrE3CGx/1332-Private-Experience?node-id=1446%3A113294&t=T8JlGR70j6nB4WpQ-4). The cohort [edition](https://github.com/Qiskit/saiba/issues/333) and [display](https://github.com/Qiskit/saiba/issues/334) component are in different issues.

This page should fetch the information from the server, display the list of cohorts and send the changes to de server when the cohorts are edited.

#### Design

https://www.figma.com/file/KCfjq5xQHg0C1JmcrE3CGx/1332-Private-Experience?node-id=1446%3A113294&t=T8JlGR70j6nB4WpQ-4

<img width="607" alt="image" src="https://user-images.githubusercontent.com/22047320/205073820-e214c910-f6f9-4826-a272-a3917c2796bb.png">

**Comment by abdonrd** [comment]
Closed by https://github.com/Qiskit/saiba/pull/352
