### ISSUE TITLE
Disable the "next" button & links for courses with Flow Control

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/saiba#357]
### Feature description

To create a flow control within a course, we need to disable the following items

- the page's `Next` navigation button
- as well as all unit link in the sidebar nav

### Dependencies

Depends on:

- https://github.com/Qiskit/saiba/issues/385

### Additional information

[Figma designs](https://www.figma.com/file/KCfjq5xQHg0C1JmcrE3CGx/1332-Private-Experience?node-id=1881%3A160648&t=BhvXTtvCuiYb9AR9-4)

**Comment by yoshiemuranaka** [comment]
resolved by https://github.com/Qiskit/saiba/pull/416
