### ISSUE TITLE
Change routes of the Account pages

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/saiba#375]
### Feature description

After discussing our strategy to define the available routes in Saiba, we need to make some changes to the Account pages.

### Dependencies

Depends on:

- https://github.com/Qiskit/saiba/issues/316

**Comment by abdonrd** [comment]
### Account

- `/account/learn`: Content explorer
- `/account/teach`: Content management
- `/account/profile`: Profile information

**Comment by abdonrd** [comment]
Done!
