### ISSUE TITLE
Change routes of the Public Textbook courses

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/saiba#377]
### Feature description

After discussing our strategy to define the available routes in Saiba, we need to make some changes to the Public Textbook courses pages.

### Dependencies

Depends on:

- https://github.com/Qiskit/saiba/issues/316

**Comment by abdonrd** [comment]
### Routes

- `/course/:courseSlug`: Course home
- `/course/:courseSlug/:unitSlug`: Course unit

**Comment by abdonrd** [comment]
Done!
