### ISSUE TITLE
Change routes of the Private courses

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/saiba#378]
### Feature description

After discussing our strategy to define the available routes in Saiba, we need to make some changes to the Private courses pages.

### Dependencies

Depends on:

- https://github.com/Qiskit/saiba/issues/316

**Comment by abdonrd** [comment]
### Routes

- `/account/teach/course/:courseSlug/edit`: Course management (and its cohorts)
- ~`/account/teach/course/:courseSlug/cohort/create`~: Cohort create
  (right now, we do it in the course management page)
- ~`/account/teach/course/:courseSlug/cohort/:cohortId/edit`~: Cohort edit
  (right now, we do it in the course management page)
- `/course/:courseSlug/:unitSlug`: Cohort course unit
- `/cohort-enrollment/:enrollmentCode`: Cohort enrollment

Source: https://github.com/Qiskit/saiba/issues/380#issuecomment-1335252916

**Comment by abdonrd** [comment]
Done!
