### ISSUE TITLE
Change routes of the Syllabi pages

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/saiba#379]
### Feature description

After discussing our strategy to define the available routes in Saiba, we need to make some changes to the Syllabi pages.

### Dependencies

Depends on:

- https://github.com/Qiskit/saiba/issues/316

**Comment by abdonrd** [comment]
We still not have syllabi on the project.

**Comment by vabarbosa** [comment]
there is no routes to be changed because we does not have any syllabi logic currently. we will need to think about implementing the logic and during the implementation we can make sure to properly set the routes
