### ISSUE TITLE
Update Courses with fields for Flow Control

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/saiba#385]
### Feature description

As part of Flow Control: 

- [x] we should be able to determine whether a course requires `flow_control`
- [ ] we should be able to determine if a unit is `complete`

### Additional context

If it **does not require** _flow control_, the user will be able to navigate through the course's units in any order they wish at any point in time.

Alternatively, if it **does require** _flow control_, then the user will have to access the units in order and complete all goals on each page in order to proceed to the next one.

**Comment by abdonrd** [comment]
Now we have the `flow_control` field in the API.

And we already have a `date_completed` field in the Progression for that.

**Comment by techtolentino** [comment]
Thanks @abdonrd 👏🏼
