### ISSUE TITLE
Set-up cookie consent

### ISSUE THREAD

**Issue by Tansito** [Qiskit/saiba#396]

**Comment by abdonrd** [comment]
Maybe we already have it with the analytics script, so, let's check it!

Thanks @yoshiemuranaka for the info!

**Comment by yoshiemuranaka** [comment]
https://github.ibm.com/Bluemix/Bluemix.Analytics#gdpr-and-eprivacy-compliance

>The cookie consent dialog, which allows users to set or change their cookie consent settings, will automatically be loaded and included on the page, however you are free to [customize the styling of your cookie preferences button](https://pages.github.ibm.com/Bluemix/platform-analytics/development/cookie-consent-button-styling-override/).

**Comment by yoshiemuranaka** [comment]
You can test this locally by setting `NUXT_PUBLIC_IS_ANALYTICS_ENABLED` env variable to true
