### ISSUE TITLE
Mathjax fonts are giving error

### ISSUE THREAD

**Issue by Tansito** [Qiskit/saiba#4]
### What is the expected enhancement?

There are some fonts from Mathjax that are giving error when being loaded.

**Comment by techtolentino** [comment]
Hey @eddybrando - this was not fixed. In the PR, it shows that it had to be reverted.

**Comment by abdonrd** [comment]
Looks like we have two things here:

- MathJax automatically loads their fonts.
 And we can customize the path the path with the `MathJax.chtml.fontURL` option as mentioned [here](https://github.com/mathjax/MathJax/issues/2539#issue-701173625):

  ```javascript
  MathJax = {
    chtml: {
      fontURL: 'path/to/fonts'
    }
  }
  ```

  I've tried using Nuxt's aliases, but couldn't get it to work.
  https://nuxt.com/docs/api/configuration/nuxt-config/#alias

- We have this file created by hand: [assets/scss/mathjax-fonts.scss](https://github.com/Qiskit/saiba/blob/main/assets/scss/mathjax-fonts.scss)
  But the `$mathjax-font-path` is wrong. I think we should use the Nuxt alias.
  As we did it here: https://github.com/Qiskit/saiba/pull/428
