### ISSUE TITLE
Bug: Qiskit Learn Page Tab placement

### ISSUE THREAD

**Issue by gracelindsell** [Qiskit/saiba#408]
### Where does the issue happen?

https://qiskit.org/learn/

### What is the content issue?

The Learn and Teach tabs should be flush right instead of left. The designs in Figma are up to date in the 1260 Curated Syllabus file

### Screenshots

<img width="1325" alt="Screen Shot 2022-12-12 at 8 08 21 AM" src="https://user-images.githubusercontent.com/89415444/207925035-024e4435-457b-4f8a-99e7-f45db3b252a9.png">

**Comment by techtolentino** [comment]
Closing this here since the code for this is in the Qiskit org site repo:
__
**Duplicate:** https://github.com/Qiskit/qiskit.org/issues/2891
**Related:** https://github.com/Qiskit/qiskit.org/issues/2889
