### ISSUE TITLE
Restrict API access for flow controlled unit content

### ISSUE THREAD

**Issue by yoshiemuranaka** [Qiskit/saiba#430]
We want to enforce unit content permissions from the API when a course has flow control enabled (units should be completed in order). The current implementation in #422 only handles UI (frontend) content restriction. 

After discussing with @abdonrd, we want to confirm whether or not the API level restriction is necessary.  Since flow control is mostly acting as a small friction point (eg clicking a checkbox) is the frontend-only implementation sufficient?

>Looks good! But we should control this from the API, not from the front. So this could be a temporary patch, eventually (when it's in the API) we should roll it back.

_Originally posted by @abdonrd in https://github.com/Qiskit/saiba/pull/422#pullrequestreview-1229373519_

**Comment by yoshiemuranaka** [comment]
@JRussellHuffman @gracelindsell we'd like to get your thoughts here

**Comment by abdonrd** [comment]
As Yoshie mentions, it may not be necessary to block access from the API (which is possible, but more complicated than hiding visually from the front), since the blocking is due to a small friction point (clicking the checkbox)

**Comment by yoshiemuranaka** [comment]
Confirmed the frontend restriction is sufficient for the MVP
@abdonrd @vabarbosa not sure if we should close this issue or keep it open for revisiting in the future

**Comment by vabarbosa** [comment]
@yoshiemuranaka i would close this and open a new one specifically for the API

**Comment by yoshiemuranaka** [comment]
Moved issue to saiba api repo
