### ISSUE TITLE
As a developer, I would like to have the layout of the different pages to just fill the spaces with the needed components

### ISSUE THREAD

**Issue by Tansito** [Qiskit/saiba#49]
### Background

Right now saiba will need to support a good amount of different layouts for the different pages. We would like to use [Nuxt layouts](https://v3.nuxtjs.org/guide/directory-structure/layouts/) feature so implement reusable layouts to improve the maintainability.

### Goal

Implement the needed architecture to support different layouts in the application.

### Acceptance criteria

- [x] Base layout
- [x] Unit layout
- [x] User layout
- [x] Sign-in layout
- [x] Setup of the main elements in the structure (navbar & side-bars)

### Tasks

The tasks for this feature are being managed through this [milestone](https://github.com/Qiskit/saiba/milestone/9) divided in the next tasks:
- https://github.com/Qiskit/saiba/issues/13
- https://github.com/Qiskit/saiba/issues/14
- https://github.com/Qiskit/saiba/issues/15
- https://github.com/Qiskit/saiba/issues/50
- https://github.com/Qiskit/saiba/issues/40
- https://github.com/Qiskit/saiba/issues/41
- https://github.com/Qiskit/saiba/issues/42

**Comment by vabarbosa** [comment]
all tasks completed
